[package]
name = "carbon-timescaledb"
version = "0.0.1"
authors = ["Dan Aharon <dan@danielaharon.com>"]
edition = "2018"

[dependencies]
jemallocator = "0.1.9"
itertools = "0.8.0"
nom = "4.1.1"
postgres = "0.15.2"
