[package]
name = "carbon-timescaledb"
version = "0.0.1"
authors = ["Dan Aharon <dan@danielaharon.com>"]
edition = "2018"

[dependencies]
jemallocator = "0.1.9"
log = "0.4.6"
simplelog = "0.5.3"
clap = "2.32.0"
rayon = "1.0.3"
crossbeam-channel = "0.3.4"
postgres = "0.15.2"
